version: 0.0
os: linux
files:
  - source: /
    destination: $HOME/wishlist_GQL
    runas: ubuntu
hooks:
  BeforeInstall:
      - location: $HOME/wishlist_GQL/scripts/before_install.sh
  AfterInstall:
      - location: $HOME/wishlist_GQL/scripts/after_install.sh