version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/wishlist_GQL
hooks:
  AfterInstall:
   - location: ../ci_cd_script.sh
   - location: scripts/install_app_dependencies.sh
     timeout: 30
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 30
     runas: root