version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/wishlist_GQL
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 30
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 30
     runas: root