version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wishlist_GQL
    runas: ubuntu
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 774
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh