#!/bin/bash
sudo apt install python3-pip
sudo pip install virtualenv
cd /home/ubuntu/wishlist_GQL
if [! -d /home/ubuntu/wishlist_GQL/venv]; then
    virtualenv venv
fi
source venv/bin/activate
sudo pip install -r requirements.txt